package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"samroehrich/training-freaks/gpx"
	"samroehrich/training-freaks/graph/model"
)

// CreateActivity is the resolver for the createActivity field.
func (r *mutationResolver) CreateActivity(ctx context.Context, input model.ActivityInput) (*bool, error) {
	err := r.DB.Ping()

	if err != nil {
		return nil, err
	}
	s := true
	fmt.Println("upload", input.File.Filename)

	content, err := io.ReadAll(input.File.File)

	if err != nil {
		return nil, err
	}

	var t gpx.Track

	err = json.Unmarshal(content, &t)

	if err != nil {
		return nil, err
	}

	fmt.Println(t.Name)
	return &s, nil
}

// JoinWaitlist is the resolver for the joinWaitlist field.
func (r *mutationResolver) JoinWaitlist(ctx context.Context, input model.WaitlistInput) (*bool, error) {
	s := false
	q, err := r.DB.Prepare("INSERT INTO waitlist (email) VALUES($1)")

	if err != nil {
		return &s, err
	}

	_, err = q.Exec(input.Email)

	if err != nil {
		return &s, err
	}

	s = true
	return &s, nil
}

// Activity is the resolver for the activity field.
func (r *queryResolver) Activity(ctx context.Context, name string) (*model.Activity, error) {
	err := r.DB.Ping()
	if err != nil {
		fmt.Println("nop")
	}

	res, err := r.DB.Query("SELECT * FROM activity WHERE name = ?", &name)

	if err != nil {
		return nil, err
	}

	defer res.Close()
	var activity model.Activity
	if res.Next() {
		err := res.Scan(&activity.Name, &activity.Details, &activity.Type)
		if err != nil {
			return nil, err
		}
		return &activity, nil
	}
	return &activity, nil
}

// Activities is the resolver for the activities field.
func (r *queryResolver) Activities(ctx context.Context) ([]*model.Activity, error) {
	err := r.DB.Ping()
	if err != nil {
		fmt.Println("nop")
		return nil, err
	}

	res, err := r.DB.Query("SELECT * FROM activity")
	if err != nil {
		return nil, err
	}
	defer res.Close()

	var activities []*model.Activity
	for res.Next() {
		var activity model.Activity
		err := res.Scan(&activity.Type, &activity.Details, &activity.Name)

		if err != nil {
			return nil, err
		}

		activities = append(activities, &activity)
	}

	return activities, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
