// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type Activity struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Details string `json:"details"`
	Type    string `json:"type"`
}

type ActivityInput struct {
	Name     string         `json:"name"`
	Upload   graphql.Upload `json:"upload"`
	Category string         `json:"category"`
}

type WaitlistInput struct {
	Email string `json:"email"`
}
